#!/usr/bin/env python3

from __future__ import annotations

import argparse
import configparser
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "godot-plugin" / "addons" / "gotamata_agent_bridge" / "bridge_contract.json"
PLUGIN_PATH = ROOT / "godot-plugin" / "addons" / "gotamata_agent_bridge" / "plugin.gd"
PLUGIN_CFG_PATH = ROOT / "godot-plugin" / "addons" / "gotamata_agent_bridge" / "plugin.cfg"
ADDON_README_PATH = ROOT / "godot-plugin" / "addons" / "gotamata_agent_bridge" / "README.md"
SKILL_PATH = ROOT / "agent-skill" / "godot-editor-agent-bridge" / "SKILL.md"
PROTOCOL_PATH = ROOT / "agent-skill" / "godot-editor-agent-bridge" / "references" / "protocol.md"

README_MARKER_BEGIN = "<!-- BEGIN GENERATED BRIDGE COMMANDS -->"
README_MARKER_END = "<!-- END GENERATED BRIDGE COMMANDS -->"
SKILL_MARKER_BEGIN = "<!-- BEGIN GENERATED BRIDGE SNAPSHOT -->"
SKILL_MARKER_END = "<!-- END GENERATED BRIDGE SNAPSHOT -->"

CATEGORY_ORDER = ["core", "editor", "pipeline"]
CATEGORY_LABELS = {
    "core": "Core",
    "editor": "Editor",
    "pipeline": "Pipeline",
}


def load_contract() -> dict:
    return json.loads(CONTRACT_PATH.read_text())


def load_plugin_cfg() -> configparser.ConfigParser:
    parser = configparser.ConfigParser()
    parser.read(PLUGIN_CFG_PATH)
    return parser


def cfg_value(parser: configparser.ConfigParser, section: str, option: str) -> str:
    return parser.get(section, option).strip().strip('"')


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def extract_dispatch_commands() -> list[str]:
    source = PLUGIN_PATH.read_text()
    match = re.search(
        r"func _execute_agent_command\(command: String, args: Dictionary\) -> Dictionary:\n(?P<body>.*?)(?:\nfunc _cmd_editor_state|\Z)",
        source,
        re.S,
    )
    require(match is not None, "Could not find _execute_agent_command in plugin.gd")
    body = match.group("body")
    commands = re.findall(r'^\s+"([^"]+)":\s*$', body, re.M)
    require(commands, "No dispatch commands found in plugin.gd")
    return commands


def format_args_inline(args: list[dict]) -> str:
    if not args:
        return "none"
    items = []
    for arg in args:
        label = arg["name"]
        if not arg.get("required", False):
            label += " optional"
        items.append(label)
    return ", ".join(items)


def render_addon_readme_block(contract: dict) -> str:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for command in contract["commands"]:
        grouped[command["category"]].append(command)

    lines = ["## Commands", ""]
    for category in CATEGORY_ORDER:
        commands = grouped.get(category, [])
        if not commands:
            continue
        lines.append(f"### {CATEGORY_LABELS[category]}")
        for command in commands:
            lines.append(
                f"- `{command['name']}` (`args`: {format_args_inline(command['args'])})"
            )
        lines.append("")

    lines.append(
        "`call` targets are currently: "
        + ", ".join(f"`{target}`" for target in contract["call_targets"])
        + "."
    )
    return "\n".join(lines).strip() + "\n"


def render_skill_block(contract: dict) -> str:
    grouped: dict[str, list[str]] = defaultdict(list)
    for command in contract["commands"]:
        grouped[command["category"]].append(command["name"])

    transport = contract["transport"]
    lines = [
        "- Transport: `%s:%s` over %s." % (
            transport["host"],
            transport["port"],
            transport["framing"],
        ),
    ]
    for category in CATEGORY_ORDER:
        names = grouped.get(category, [])
        if not names:
            continue
        lines.append(
            "- %s commands: %s."
            % (
                CATEGORY_LABELS[category],
                ", ".join(f"`{name}`" for name in names),
            )
        )
    lines.append("- Full argument and result details are generated in `references/protocol.md`.")
    return "\n".join(lines) + "\n"


def render_protocol(contract: dict) -> str:
    plugin = contract["plugin"]
    transport = contract["transport"]
    grouped: dict[str, list[dict]] = defaultdict(list)
    for command in contract["commands"]:
        grouped[command["category"]].append(command)

    lines = [
        "# GoTamata Godot Asset Pipeline Protocol",
        "",
        "<!-- Generated by tools/sync_bridge_contract.py. Do not edit manually. -->",
        "",
        "## Plugin",
        "",
        f"- Name: `{plugin['name']}`",
        f"- Slug: `{plugin['slug']}`",
        f"- Version: `{plugin['version']}`",
        "",
        "## Transport",
        "",
        f"- TCP server (default `{transport['host']}:{transport['port']}`)",
        f"- {transport['framing'].capitalize()} (one request object per line)",
        "",
        "## Request Shape",
        "",
        "```json",
        '{',
        '  "id": "req-123",',
        '  "token": "optional-shared-secret",',
        '  "command": "editor_state",',
        '  "args": {}',
        '}',
        "```",
        "",
        "## Response Shape",
        "",
        "```json",
        '{',
        '  "ok": true,',
        '  "id": "req-123",',
        '  "command": "editor_state"',
        '}',
        "```",
        "",
        "Error format:",
        "",
        "```json",
        '{',
        '  "ok": false,',
        '  "error": {',
        '    "code": "error_code",',
        '    "message": "human readable"',
        "  }",
        '}',
        "```",
        "",
        "## Commands",
        "",
    ]

    for category in CATEGORY_ORDER:
        commands = grouped.get(category, [])
        if not commands:
            continue
        lines.append(f"### {CATEGORY_LABELS[category]}")
        lines.append("")
        for command in commands:
            lines.append(f"#### `{command['name']}`")
            lines.append(f"- Purpose: {command['description']}")
            if command["args"]:
                lines.append("- Args:")
                for arg in command["args"]:
                    label = f"`{arg['name']}`"
                    if not arg.get("required", False):
                        label += " optional"
                    lines.append(f"  - {label}: {arg['description']}")
            else:
                lines.append("- Args: none")
            lines.append(f"- Result: {command['result']}")
            lines.append("")

    lines.extend(
        [
            "## Call Targets",
            "",
            "- Allowed `call.target` values: "
            + ", ".join(f"`{target}`" for target in contract["call_targets"])
            + ".",
            "",
            "## Notes",
            "",
        ]
    )
    for note in contract["notes"]:
        lines.append(f"- {note}")
    lines.append("")
    return "\n".join(lines)


def replace_managed_block(path: Path, begin: str, end: str, replacement: str) -> str:
    source = path.read_text()
    pattern = re.compile(
        rf"{re.escape(begin)}\n.*?{re.escape(end)}",
        re.S,
    )
    require(
        pattern.search(source) is not None,
        f"Could not find managed block in {path.relative_to(ROOT)}",
    )
    return pattern.sub(f"{begin}\n{replacement}{end}", source)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text() if path.exists() else ""
    changed = existing != content
    if check:
        return changed
    if changed:
        path.write_text(content)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    contract = load_contract()
    plugin_cfg = load_plugin_cfg()
    dispatch_commands = extract_dispatch_commands()
    contract_commands = [command["name"] for command in contract["commands"]]

    require(
        dispatch_commands == contract_commands,
        "bridge_contract.json command order does not match plugin.gd dispatch.\n"
        f"contract={contract_commands}\nplugin={dispatch_commands}",
    )
    require(
        cfg_value(plugin_cfg, "plugin", "version") == contract["plugin"]["version"],
        "bridge_contract.json plugin.version does not match plugin.cfg version",
    )
    require(
        cfg_value(plugin_cfg, "plugin", "name") == contract["plugin"]["name"],
        "bridge_contract.json plugin.name does not match plugin.cfg name",
    )

    changed_paths: list[Path] = []

    addon_readme = replace_managed_block(
        ADDON_README_PATH,
        README_MARKER_BEGIN,
        README_MARKER_END,
        render_addon_readme_block(contract),
    )
    if write_or_check(ADDON_README_PATH, addon_readme, args.check):
        changed_paths.append(ADDON_README_PATH)

    skill_text = replace_managed_block(
        SKILL_PATH,
        SKILL_MARKER_BEGIN,
        SKILL_MARKER_END,
        render_skill_block(contract),
    )
    if write_or_check(SKILL_PATH, skill_text, args.check):
        changed_paths.append(SKILL_PATH)

    protocol_text = render_protocol(contract)
    if write_or_check(PROTOCOL_PATH, protocol_text, args.check):
        changed_paths.append(PROTOCOL_PATH)

    if args.check and changed_paths:
        print("Generated bridge files are out of date:")
        for path in changed_paths:
            print(f"- {path.relative_to(ROOT)}")
        return 1

    if not args.check:
        for path in changed_paths:
            print(f"updated {path.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
